apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service-uc123
  namespace: rota-maravilhosa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-service-uc123
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: data-service-uc123
    spec:
      containers:
      - name: data-service-uc123
        image: us-west4-docker.pkg.dev/proj1cc-493515/rota-maravilhosa/data-service-uc123:latest
        ports:
        - containerPort: 8004
        resources:
          requests:
            cpu: "50m"
            memory: "512Mi"
          limits:
            cpu: "200m"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /ready
            port: 8004
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              key: API_TOKEN
              name: bq-secret
        envFrom:
        - configMapRef:
            name: rota-maravilhosa-config