apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: rota-maravilhosa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:latest
        args: [ "start-dev" ]
        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_PROXY
          value: edge
        - name: KC_HTTP_ENABLED
          value: "true"
        ports:
        - containerPort: 8080
