apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: rota-maravilhosa
  annotations:
    cloud.google.com/backend-config: '{"default": "api-gateway-hc"}'
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
  - port: 8000
    targetPort: 8000
