apiVersion: v1
kind: Service
metadata:
  name: data-service-uc8-uc11
  namespace: rota-maravilhosa
spec:
  selector:
    app: data-service-uc8-uc11
  ports:
  - protocol: TCP
    port: 8007
    targetPort: 8007