apiVersion: v1
kind: Service
metadata:
  name: route-service-uc7
  namespace: rota-maravilhosa
spec:
  selector:
    app: route-service-uc7
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8003