# hpa api-gateway
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
  namespace: rota-maravilhosa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 2
  maxReplicas: 10
  metrics: 
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60
--- #hpa prediction_service_uc5_uc6
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: prediction-service-uc5-uc6-hpa
  namespace: rota-maravilhosa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prediction_service_uc5_uc6
  minReplicas: 2
  maxReplicas: 8
  metrics: 
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
--- #hpa data_service_uc4
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: data-service-uc4-hpa
  namespace: rota-maravilhosa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data_service_uc4
  minReplicas: 2
  maxReplicas: 8
  metrics: 
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
--- #hpa route_service_uc7
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: route-service-uc4-hpa
  namespace: rota-maravilhosa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data_service_uc4
  minReplicas: 1
  maxReplicas: 6
  metrics: 
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60

--- #hpa prediction_service_uc9_uc10
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: prediction-service-uc9_uc10-hpa
  namespace: rota-maravilhosa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prediction-service-uc9_uc10
  minReplicas: 1
  maxReplicas: 7
  metrics: 
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
#--- #hpa data_service_uc123
--- #hpa data_service_uc8_uc11
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: data-service-uc8-uc11-hpa
  namespace: rota-maravilhosa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data_service_uc8_uc11
  minReplicas: 2
  maxReplicas: 8
  metrics: 
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60
