apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rota-maravilhosa-ingress
  namespace: rota-maravilhosa
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  ingressClassName: gce
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 8000
