apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: api-gateway-vpa
  namespace: rota-maravilhosa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: api-gateway
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledResources: [ "cpu", "memory" ]
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prediction-service-uc5-uc6-vpa
  namespace: rota-maravilhosa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: prediction-service-uc5-uc6
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledResources: [ "cpu", "memory" ]
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: data-service-uc8-uc11-vpa
  namespace: rota-maravilhosa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: data-service-uc8-uc11
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledResources: [ "cpu", "memory" ]
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: route-service-uc7-vpa
  namespace: rota-maravilhosa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: route-service-uc7
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledResources: [ "cpu", "memory" ]
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prediction-service-uc9-uc10-vpa
  namespace: rota-maravilhosa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: prediction-service-uc9-uc10
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledResources: [ "cpu", "memory" ]
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: data-service-uc123-vpa
  namespace: rota-maravilhosa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: data-service-uc123
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledResources: [ "cpu", "memory" ]
